In [2]:
import pandas as pd
import numpy as nd

In [3]:
import matplotlib.pyplot as plt

In [4]:
url = " https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal_length','sepal_width','petal_length','petal_width','class']
df = pd.read_csv(url,names=names)

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
df

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
independent = df.drop(['class'],axis = 'columns')
dependent = df['class']

In [8]:
independent

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
dependent.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

In [10]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.20)

In [16]:
x_train.head()

sepal_length  sepal_width  petal_length  petal_width
97            6.2          2.9           4.3          1.3
135           7.7          3.0           6.1          2.3
129           7.2          3.0           5.8          1.6
79            5.7          2.6           3.5          1.0
89            5.5          2.5           4.0          1.3

In [17]:
x_test.head()

sepal_length  sepal_width  petal_length  petal_width
53            5.5          2.3           4.0          1.3
85            6.0          3.4           4.5          1.6
132           6.4          2.8           5.6          2.2
103           6.3          2.9           5.6          1.8
87            6.3          2.3           4.4          1.3

In [18]:
y_train.head()

97     Iris-versicolor
135     Iris-virginica
129     Iris-virginica
79     Iris-versicolor
89     Iris-versicolor
Name: class, dtype: object

In [20]:
model = tree.DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [21]:
model.score(x_train,y_train)

1.0

In [23]:
y_pred = model.predict(x_test)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

[[ 9  0  0]
 [ 0  9  0]
 [ 0  1 11]]


In [27]:
import matplotlib.pyplot as plt

In [36]:
plt.figure(figsize = (120,80))
plot_tree(model,filled = True, feature_names = df.columns)

[Text(0.3, 0.9285714285714286, 'petal_length <= 2.35\ngini = 0.666\nsamples = 120\nvalue = [41, 41, 38]'),
 Text(0.2, 0.7857142857142857, 'gini = 0.0\nsamples = 41\nvalue = [41, 0, 0]'),
 Text(0.4, 0.7857142857142857, 'petal_length <= 4.75\ngini = 0.499\nsamples = 79\nvalue = [0, 41, 38]'),
 Text(0.3, 0.6428571428571429, 'gini = 0.0\nsamples = 36\nvalue = [0, 36, 0]'),
 Text(0.5, 0.6428571428571429, 'petal_width <= 1.75\ngini = 0.206\nsamples = 43\nvalue = [0, 5, 38]'),
 Text(0.2, 0.5, 'petal_length <= 4.95\ngini = 0.5\nsamples = 8\nvalue = [0, 4, 4]'),
 Text(0.1, 0.35714285714285715, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.3, 0.35714285714285715, 'petal_width <= 1.55\ngini = 0.444\nsamples = 6\nvalue = [0, 2, 4]'),
 Text(0.2, 0.21428571428571427, 'gini = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(0.4, 0.21428571428571427, 'petal_length <= 5.45\ngini = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Text(0.3, 0.07142857142857142, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]')